//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVEMon.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
        ///&gt;
        ///  &lt;xsl:strip-space elements=&quot;*&quot;/&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;@* | node()&quot;&gt;
        ///      &lt;xsl:copy&gt;
        ///          &lt;xsl:apply-templates select=&quot;@* | node()&quot;/&gt;
        ///      &lt;/xsl:copy&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;!-- Rowsets are transformed into something else--&gt;
        ///  &lt;xsl:template match [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string RowsetsXSLT {
            get {
                return ResourceManager.GetString("RowsetsXSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
        ///&gt;
        ///    &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;!-- Root --&gt;
        ///  &lt;xsl:template match=&quot;logindata2&quot;&gt;
        ///    &lt;xsl:element name=&quot;OldSettings&quot;&gt;
        ///      &lt;xsl:element name=&quot;accounts&quot;&gt;
        ///        &lt;xsl:for-each select=&quot;Accounts/AccountDetails&quot;&gt;
        ///          &lt;xsl:call-template name=&quot;account&quot;/&gt;
        ///        &lt;/xsl:for-each&gt;
        ///   [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SettingsAndPlanImport {
            get {
                return ResourceManager.GetString("SettingsAndPlanImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
        ///  &lt;xsl:template match=&quot;outputCharacter&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;title&gt;
        ///          Character Sheet :: &lt;xsl:value-of select=&quot;@name&quot;/&gt;
        ///        &lt;/title&gt;
        ///      &lt;/head&gt;
        ///      &lt;body&gt;
        ///        &lt;table&gt;
        ///          &lt;tr&gt;
        ///            &lt;td&gt;
        ///              &lt;xsl:element name=&quot;img&quot;&gt;
        ///                &lt;xsl:attribute name=&quot;src&quot;&gt;
        ///                  http://img.eve.is/serv.asp?s=256&amp;amp;c=&lt;xsl: [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string XmlToHtmlXslt {
            get {
                return ResourceManager.GetString("XmlToHtmlXslt", resourceCulture);
            }
        }
    }
}
