//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.Common.Net {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVEMon.Common.Net.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A request to {0} failed because EVEMon was unable to connect to the server. Please check your network and/or firewall settings..
        /// </summary>
        internal static string ConnectFailure {
            get {
                return ResourceManager.GetString("ConnectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A file request to {0} failed because the file could not be written..
        /// </summary>
        internal static string FileException {
            get {
                return ResourceManager.GetString("FileException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An Image request  to {0} failed because the server did not return a valid image..
        /// </summary>
        internal static string ImageException {
            get {
                return ResourceManager.GetString("ImageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A request to {0} failed because the name resolver service could not resolve the host name. Please check your network settings..
        /// </summary>
        internal static string NameResolutionFailure {
            get {
                return ResourceManager.GetString("NameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The proxy server at {0} rejected a request to {1}. Please verify that you have specified the correct user name and password..
        /// </summary>
        internal static string ProxyAuthenticationFailure {
            get {
                return ResourceManager.GetString("ProxyAuthenticationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The proxy server at {0} rejected a request to {1}. Please verify that you have specified the correct user name and password. Web requests have been temporarily disabled until your proxy settings have been updated..
        /// </summary>
        internal static string ProxyAuthenticationFailureDisabledRequests {
            get {
                return ResourceManager.GetString("ProxyAuthenticationFailureDisabledRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The name resolver service could not resolve the proxy host name &quot;{0}&quot;. Please verify that you have specified the correct proxy server, or check your network settings..
        /// </summary>
        internal static string ProxyNameResolutionFailure {
            get {
                return ResourceManager.GetString("ProxyNameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The maximum number of redirects was exceeded while attempting to retrieve data from {0}..
        /// </summary>
        internal static string RedirectsExceeded {
            get {
                return ResourceManager.GetString("RedirectsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A request to {0} was not permitted by the proxy at {1}..
        /// </summary>
        internal static string RequestProhibitedByProxy {
            get {
                return ResourceManager.GetString("RequestProhibitedByProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A request to {0} failed because web requests have been temporarily disabled..
        /// </summary>
        internal static string RequestsDisabled {
            get {
                return ResourceManager.GetString("RequestsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The web server at {0} returned an error. The full response returned by the web server was:.
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A request to {0} failed because no response was received during the timeout period..
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A request to {0} failed with status {1}..
        /// </summary>
        internal static string UnknownWebException {
            get {
                return ResourceManager.GetString("UnknownWebException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A Xml request to {0} failed because the server did not return a valid Xml document.
        /// </summary>
        internal static string XmlException {
            get {
                return ResourceManager.GetString("XmlException", resourceCulture);
            }
        }
    }
}
