//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVEMon.Common.Serialization.Datafiles {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DatafileConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatafileConstants() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EVEMon.Common.Serialization.Datafiles.DatafileConstants", typeof(DatafileConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a eve-certificates-en-US.xml.gz.
        /// </summary>
        public static string CertificatesDatafile {
            get {
                return ResourceManager.GetString("CertificatesDatafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a eve-geography-en-US.xml.gz.
        /// </summary>
        public static string GeographyDatafile {
            get {
                return ResourceManager.GetString("GeographyDatafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a eve-items-en-US.xml.gz.
        /// </summary>
        public static string ItemsDatafile {
            get {
                return ResourceManager.GetString("ItemsDatafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a eve-properties-en-US.xml.gz.
        /// </summary>
        public static string PropertiesDatafile {
            get {
                return ResourceManager.GetString("PropertiesDatafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a eve-reprocessing-en-US.xml.gz.
        /// </summary>
        public static string ReprocessingDatafile {
            get {
                return ResourceManager.GetString("ReprocessingDatafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a eve-skills-en-US.xml.gz.
        /// </summary>
        public static string SkillsDatafile {
            get {
                return ResourceManager.GetString("SkillsDatafile", resourceCulture);
            }
        }
    }
}
