//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.EVEMon.Common.Net {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.EVEMon.Common.Net.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&apos;1.0&apos; encoding=&apos;UTF-8&apos;?&gt;
        ///&lt;eveapi version=&quot;2&quot;&gt;
        ///  &lt;currentTime&gt;2008-10-01 22:57:11&lt;/currentTime&gt;
        ///  &lt;result&gt;
        ///    &lt;characterID&gt;1026504290&lt;/characterID&gt;
        ///    &lt;name&gt;Sharak&apos;nor&lt;/name&gt;
        ///    &lt;race&gt;Minmatar&lt;/race&gt;
        ///    &lt;bloodLine&gt;Vherokior&lt;/bloodLine&gt;
        ///    &lt;gender&gt;Male&lt;/gender&gt;
        ///    &lt;corporationName&gt;Republic University&lt;/corporationName&gt;
        ///    &lt;corporationID&gt;1000171&lt;/corporationID&gt;
        ///    &lt;cloneName&gt;Clone Grade Alpha&lt;/cloneName&gt;
        ///    &lt;cloneSkillPoints&gt;900000&lt;/cloneSkillPoints&gt;
        ///    &lt;balance&gt;5000.00&lt;/bal [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CharacterSheet {
            get {
                return ResourceManager.GetString("CharacterSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap testimage {
            get {
                object obj = ResourceManager.GetObject("testimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
